name: Release Revit Plugins

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: "Build and release the Revit Plugins"
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        
      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1.0.0
        
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1

      - name: Nuget Restore
        run: nuget restore 
          
      - name: MSBuild Revit 2021
        working-directory: Honeybee.Revit.2021
        run: |
          msbuild /p:Configuration=Release
          
      - name: MSBuild Revit 2020
        working-directory: Honeybee.Revit.2020
        run: |
          msbuild /p:Configuration=Release
          
      - name: MSBuild Revit 2019
        working-directory: Honeybee.Revit.2019
        run: |
          msbuild /p:Configuration=Release
                    
      - name: Zip Build Artifact
        run: |
          Compress-Archive -U -Path Honeybee.Revit.2021\bin\Release\* -DestinationPath HoneybeeRevit2021
          Compress-Archive -U -Path Honeybee.Revit.2020\bin\Release\* -DestinationPath HoneybeeRevit2020
          Compress-Archive -U -Path Honeybee.Revit.2019\bin\Release\* -DestinationPath HoneybeeRevit2019
          
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
